package com.utils;

public interface Sources {
    String xz_test_base_url="https://gateway-service-ts.wetax.com.cn/walkerfestivalapi-service/api";

    String xz_master_base_url="https://gateway-service.wetax.com.cn/walkerfestivalapi-service/api";

    String xz_test_Authorization="bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJFM0Q0NDE1NDE5RjA1MjdCNUJGNzIzRTZBQzMwNTUxMEE3N0Q" +
            "zOTYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJ2ajFFRlVHZkJTZTF2M0ktYXNNRlVRcDMwNVkifQ.eyJuYmYiOjE2NjQ1MjkxMzQsImV4cCI6MTY2NTUy" +
            "OTEzNCwiaXNzIjoiaHR0cDovLzEwLjMwLjExMi4zOSIsImF1ZCI6ImFwaTEiLCJzdWIiOiI4MTNkMWRmZC0zMmNjLTQ2ZmQtYjZkOS1mYjcxN" +
            "zBjNTEwNDQiLCJ1c2VyaWQiOiI4MTNkMWRmZC0zMmNjLTQ2ZmQtYjZkOS1mYjcxNzBjNTEwNDQiLCJzZXNzaW9uX2tleSI6Ijg1UU1vbkQ3NDc2Q" +
            "XpaQVJCWC9BN2c9PSJ9.IhJ69t20MW6pX7tfnDX2FplLCHPrw6BHzRTPT_OcZppKT1OFRLfOLHELDi6geJrcI0YcNgVq2a0VNMSpGugn_SmBjjgy2" +
            "51xUWpblqAiPOsyjYgOZXr4RH3uYeOhgrpCZIU99mlm1bN-kBRZcSmup3pg-ua1zVqdb94aLMfT-ncphCt6NzJByXWU_AcZbrVIbFLii_49yETVjiuf" +
            "dUWEpkm6np2fUwyJ2PUXuQiX2LTHSpjasOdWCOo0l3Dm2yoOgZWXiRn-wYft_W0E-UXwZ2UFJpiEUbLwwzZ5fpLUJbjnW4_5i5qx0ybyY49jY4qF_EkE-r9IsKCIaoLfjDgONw";

    String xz_master_Authorization="bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJFM0Q0NDE1NDE5RjA1MjdCNUJGNzIzRTZBQzMwNTUxMEE3N0QzOTYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJ2ajFFRlVHZkJTZTF2M0ktYXNNRlVRcDMwNVkifQ.eyJuYmYiOjE2Njc5ODA4NjMsImV4cCI6MTY2ODk4MDg2MywiaXNzIjoiaHR0cDovLzEwLjMwLjUuMTk6MzcwMDMiLCJhdWQiOiJhcGkxIiwic3ViIjoiZWRiOTlhYWYtMjc4MC00NmIzLTgzMzgtYWI3NDdkYzBjMDUxIiwidXNlcmlkIjoiZWRiOTlhYWYtMjc4MC00NmIzLTgzMzgtYWI3NDdkYzBjMDUxIiwic2Vzc2lvbl9rZXkiOiJKVUdqNk9UWTBTQkFOOVowRkhHcW5nPT0ifQ.D2X_nqF-ti--qPU3trCC3EZ3JeH5MtvIG9uKYu-Dx9mKPCJ-vZI28HMSs-0xEDgBEVLdIiMdow3-56cg3uH_rAsXX_xWFAmZ2ktQlA7dEg49-bKmnsMEuSqUzHD46FofwfDg0MCfDG1NiPqCPY2vnmomfa0U4fIe5sFOfsLp1P-ozsbkJKPXy31eumDGfAkRj8Xm8oslbwNf" +
            "38Dm6tO9UueejFYqBMyWY8gmS5V-f3ttICxbEQC0z45OpeNAIwaIvv35H8Uv1tpZlgHnBIzH4u3jeHGs-y-NlykGawK913wgGl6H8Bwq4LB-CLvX-Tfrj96FlrY9nC8dZjI4IKpSeQ";

    String wns_test_base_url="https://wns-ts.wetax.com.cn/api";

    String wns_master_base_url="https://wns.wetax.com.cn/api";

    String wns_test_Authorization="";

    String wns_master_Authorization="bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJFM0Q0NDE1NDE5RjA1MjdCNUJGNzIzRTZBQzMwNTUxMEE3N0QzOTYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJ2ajFFRlVHZkJTZTF2M0ktYXNNRlVRcDMwNVkifQ.eyJuYmYiOjE2Njc5ODExMzIsImV4cCI6MTY2ODk4MTEzMiwiaXNzIjoiaHR0cDovLzEwLjMwLjUuMTk6MzcwMDMiLCJhdWQiOiJhcGkxIiwic3ViIjoiNDE4N2Q3MGQtYTlkYS00NmEwLTlhMzQtYTkyMmI3MjNkZDU3IiwiQXNwTmV0LklkZW50aXR5LlNlY3VyaXR5U3RhbXAiOiI2QUpPNEYzUUpQNEI1MkZaTk9WV0lQRlRZRFA0MlZOVCIsInByZWZlcnJlZF91c2VybmFtZSI6IndldGF4MjEwNTIwMTUyMzM3MjMzNzg5MCIsIm5hbWUiOiJ3ZXRheDIxMDUyMDE1MjMzNzIzMzc4OTAiLCJwaG9uZV9udW1iZXIiOiIxMzcxNzg4ODMxNCIsInBob25lX251bWJlcl92ZXJpZmllZCI6ZmFsc2UsInVzZXJpZCI6IjQxODdkNzBkLWE5ZGEtNDZhMC05YTM0LWE5MjJiNzIzZGQ1NyIsInNlc3Npb25fa2V5IjoiVHNmU2FKcnpHamhIbDg5QXU1WWc0Zz09In0.h042Uy_AeG4y11miPRQrB8_6CUwEwL6Q22DPm7Cq7nP9xGZEzOkxDQbW8tWqYcs9-LMKEqzRV69eqHjTR-RoJEnhu-ApGehTxOHG5VUxBRemaTV2hS4_3Zya0mre4nffHW-doVf-1rKFjMf3TAEdztUNBznbKgZ5MXThXHGzXAkE6SqxXd6Yj8_aOY9yNaejf9ZmoUxMyXIG4-lkTPCAITZSVQoms5KoZ" +
            "qtFJqlFIA3teYDFv1bO1ZEZjn0HZW4HlDh2VTqzmtntj2dTq_i8W0_Znh2QlYphctWsjMX3zzZ_52CYAxShLN3Hm_TGAEWBX3nnQk_4fQo8gRmxWlvtqg";

    String staffing_test_base_url="https://staffing-ts.wetax.com.cn/webapp/api";

    String staffing_master_base_url="https://staffing.wetax.com.cn/webapp/api";

    String staffing_test_Authorization="";

    String staffing_master_Authorization="bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJFM0Q0NDE1NDE5RjA1MjdCNUJGNzIzRTZBQzMwNTUxMEE3N0QzOTYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJ2ajFFRlVHZkJTZTF2M0ktYXNNRlVRcDMwNVkifQ.eyJuYmYiOjE2Njc5ODExMzIsImV4cCI6MTY2ODk4MTEzMiwiaXNzIjoiaHR0cDovLzEwLjMwLjUuMTk6MzcwMDMiLCJhdWQiOiJhcGkxIiwic3ViIjoiNDE4N2Q3MGQtYTlkYS00NmEwLTlhMzQtYTkyMmI3MjNkZDU3IiwiQXNwTmV0LklkZW50aXR5LlNlY3VyaXR5U3RhbXAiOiI2QUpPNEYzUUpQNEI1MkZaTk9WV0lQRlRZRFA0MlZOVCIsInByZWZlcnJlZF91c2VybmFtZSI6IndldGF4MjEwNTIwMTUyMzM3MjMzNzg5MCIsIm5hbWUiOiJ3ZXRheDIxMDUyMDE1MjMzNzIzMzc4OTAiLCJwaG9uZV9udW1iZXIiOiIxMzcxNzg4ODMxNCIsInBob25lX251bWJlcl92ZXJpZmllZCI6ZmFsc2UsInVzZXJpZCI6IjQxODdkNzBkLWE5ZGEtNDZhMC05YTM0LWE5MjJiNzIzZGQ1NyIsInNlc3Npb25fa2V5IjoiVHNmU2FKcnpHamhIbDg5QXU1WWc0Zz09In0.h042Uy_AeG4y11miPRQrB8_6CUwEwL6Q22DPm7Cq7nP9xGZEzOkxDQbW8tWqYcs9-LMKEqzRV69eqHjTR-RoJEnhu-ApGehTxOHG5VUxBRemaTV2hS4_3Zya0mre4nffHW-doVf-1rKFjMf3TAEdztUNBznbKgZ5MXThXHGzXAkE6SqxXd6Yj8_aOY9yNaejf9ZmoUxMyXIG4-lkTPCAITZSVQoms5Ko" +
            "ZqtFJqlFIA3teYDFv1bO1ZEZjn0HZW4HlDh2VTqzmtntj2dTq_i8W0_Znh2QlYphctWsjMX3zzZ_52CYAxShLN3Hm_TGAEWBX3nnQk_4fQo8gRmxWlvtqg";


    String kww_test_base_url = "https://openwhy.net";



}
